services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - clip-qdrant-net
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant/storage:/qdrant/storage
      - ./qdrant/config:/qdrant/config
    environment:
      - QDRANT_CONFIG_PATH=/qdrant/config/production.yaml

  # CLIP Server (支持CN-CLIP)
  clip-server:
    image: clip-server:0.8.3_cn-clip1.6.0
    build:
      context: .
      dockerfile: Dockerfile.clip-server
    restart: unless-stopped
    container_name: clip-server
    networks:
      - clip-qdrant-net
    ports:
      - "61000:61000"
    volumes:
      - ./search_flow.yaml:/app/search_flow.yaml # 挂载配置文件
      - ./clip_models/clip_cn_vit-b-16.pt:/app/clip_cn_vit-b-16.pt # 挂载模型文件
    environment:
      - JINA_LOG_LEVEL=DEBUG
    depends_on:
      - qdrant

  # FastAPI服务
  fastapi:
    image: clip-qdrant-api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    restart: unless-stopped
    container_name: clip-fastapi
    networks:
      - clip-qdrant-net
    ports:
      - "8000:8000"
    volumes:
      - ./clip_qdrant_server.py:/app/clip_qdrant_server.py # 挂载核心代码
      - ./clip-app:/app/clip-app # 挂载整个项目目录
    environment:
      - QDRANT_HOST=qdrant # 容器内访问Qdrant的地址
      - QDRANT_PORT=6333
      - CLIP_SERVER_HOST=clip-server # 容器内访问CLIP Server的地址
      - CLIP_SERVER_PORT=61000
    depends_on:
      - qdrant
      - clip-server

networks:
  clip-qdrant-net:
    driver: bridge
    ipam:
      config:
        - subnet: 132.132.0.0/16 # 随便挑一个没人用的段
          gateway: 132.132.0.1
