[project]
name = "clip-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clip-client>=0.8.3",
    "clip-server[search]>=0.8.3",
]
